-- LUA_PATH="/x/atmos/atmos/src/?.lua;?.lua;" lua5.4 all.lua

print "===== LEXER ====="
dofile "lexer.lua"
print "===== EXPR ====="
dofile "expr.lua"
print "===== STMT ====="
dofile "stmt.lua"
print "===== EXEC ====="
dofile "exec.lua"
print "===== TASKS ====="
dofile "tasks.lua"
print "===== CMD ====="
dofile "cmd.lua"
print "===== STREAMS ====="
dofile "streams.lua"
